---
title: "eda_ke"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(ggplot2)
library(corrplot)
library(GGally)
library(naniar)
library(readxl)
```

```{r}
# read csv file
knowledge <- read.csv2("../data/KE_data_1995-2017 final version_cluster.csv", header = TRUE, dec = ",", sep = ";")

```

```{r}
# Select subset of countries

afcountries <- c ("Algeria",	"Ethiopia", "Niger", "Angola", "Gabon", "Nigeria","Benin",
                    "Gambia",	"Rwanda", "Botswana", "Guinea Bissau", "South Africa", "Burkina Faso",
                  "Ghana", "Sao Tome and Principe", "Burundi", "Guinea", "Senegal", "Cameroon", "Kenya", "Seychelles","Cape Verde", "Lesotho", "Sierra Leone", "Central African Republic", "Liberia",	"Somalia", "Chad",	"Libya", "Sudan", "Cote d'Ivoire", "Madagascar", "Swaziland", "Comoros", "Malawi", "Tanzania", "Congo Democratic", "Mali", "Tunisia", "Congo Republic", "Mauritania", "Togo", "Djibouti", "Mauritius", "Uganda", "Egypt", "Morocco", "Zambia", "Equatorial Guinea", "Mozambique", "Zimbawe", "Eritrea", "Namibia")
```

```{r}
# Dataframe with african countries
afdata <-subset(knowledge, knowledge$Country %in% afcountries)
```

```{r}
# Generate regional dummiess
ca <- c("Angola", "Cameroon", "Cabo Verde", "Central African Republic", "Chad","Equatorial Guinea", "Eritrea", "Ethiopia",
        "Gabon", "Sao Tome and Principe")
afdata$Country.centralafrica <- ifelse(afdata$Country %in% ca,1,0)

ea <- c ("Burundi", "Comoros", "Congo Democratic Republic", "Congo Republic", "Djibouti", "Kenya",
         "Rwanda", "Seychelles", "Somalia", "Sudan", "Tanzania", "Uganda", "Zambia", "Zimbawe")

afdata$Country.eastafrica <- ifelse(afdata$Country %in% ea,1,0)

na <- c("Algeria", "Egypt", "Libya", "Mauritania", "Morocco", "Sudan", "Tunisia")
afdata$Country.northafrica <- ifelse(afdata$Country %in% na,1,0)

sa<-  c("Botswana", "Lesotho", "Madagascar", "Malawi", "Mauritius", "Mozambique", "Namibia", "South  Africa", "Swaziland")
afdata$Country.afdata <- ifelse(afdata$Country %in% sa,1,0)

wa <- c("Benin", "Burkina Faso", "Cote d'Ivoire", "Gambia", "Guinea Bissau", "Ghana", "Guinea", "Liberia", "Mali", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo")
afdata$Country.westafrica <- ifelse(afdata$Country %in% wa,1,0)
```


```{r}
summary (afdata)
```

```{r}
# Number of countries included in the sample 

countrylist = unique(afdata$Country)
length(countrylist)

# Number of time periods 

yearlist = unique(afdata$Year)
length(yearlist)
```

```{r}
# Number of missing values (% percentage)

prop_complete(afdata)
pct_miss(afdata)

#pattern of missing values in each variable
miss_var_summary(afdata[, c(3:15)])

```

```{r, warning =FALSE}
# using GGally to show a complete picture of the features to be used in the analysis

ggpairs(afdata[, c(3:15)])
```

```{r}
# Correlation matrix

m = cor(knowledge[, c(3:15)], use ="pairwise")
m
corrplot(m)

```

