---
title: "loop:imputation"
output: github_document
---


```{r}
library(naniar)
library(tidyverse)
```

```{r}

load(file= "C:/Users/anton/OneDrive/Escritorio/Clustering-Algorithms/afdata1_imputed.Rdata")
```


```{r}
# Check FIXBI2 missing values
table(is.na(afdata1_imputed$FIXBI2))
prop.table(table(is.na(afdata1_imputed$FIXBI2)))*100
```

```{r}
missing<- afdata1_imputed %>% 
  group_by(Country) %>% 
     summarise(sumNA = sum(is.na(FIXBI2))) %>% 
  print(missing, n=50)
```

```{r}
#generate loop for filling in missing values with zeros
n=length(afdata1_imputed$FIXBI2)
i=1
while (i<=n)
{
  
  if (is.na(afdata1_imputed$FIXBI2[i])) {
    afdata1_imputed$FIXBI2[i] <-0
    i=i+1
    next
  }
  
  print(paste (afdata1_imputed$Country[i], " : ",afdata1_imputed$FIXBI2[i]))
  #move to the next country
  while (afdata1_imputed$Year[i]!=1995 & i<=n){
    i=i+1
  }
}

```


```{r}
# Proportion of missing values after imputation

afdata1_imputed %>% 
  filter(is.na(FIXBI2)) %>% 
  count(Country)
```

```{r}
afdata1_imputed[afdata1_imputed$Country=="Central African Republic", c("Country","Year", "FIXBI2")]
```


```{r}
#linear imputation for the rest
library(imputeTS)
afdata1_imputed$FIXBI2 <- na.interpolation(afdata1_imputed$FIXBI2, option ="linear")
```

```{r}
afdata1_imputed[afdata1_imputed$Country=="Central African Republic", c("Country","Year", "FIXBI2")]
```

