---
title: "MixtureModels"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, eval=T}
library(GGally)
library(tidyverse)
library(ggplot2)
library(factoextra)
library(pdp)
library (mclust)
```


```{r}
# Read the dataset with imputed missing values using KNNs
afdata = read.csv("../data/afdata_imputed.csv", header = TRUE, dec = ".", sep = ",")
afdata$X = NULL

```


```{r}
scaled_data <- as.data.frame(scale(afdata[, c(3:13)]))
mclust<- Mclust(scaled_data, G=2:10)

```

```{r}
# 6 models were selected
mclust
summary(mclust, parameters = TRUE)
plot(mclust, what="BIC")
plot(mclust, what="classification")
```

```{r}
# Scatter plots for all variables and higlighting cluster groups
ggpairs(cbind(scaled_data, Cluster=as.factor(mclust$classification)),
        columns=1:11, aes(colour=Cluster, alpha=0.5),
        lower=list(continuous="points"),
        upper=list(continuous="blank"),
        axisLabels="none", switch="both")
```

```{r}
#try to interpret clusters
summary(afdata[mclust$classification==1,])
summary(afdata[mclust$classification==2,])
summary(afdata[mclust$classification==3,])
summary(afdata[mclust$classification==4,])
summary(afdata[mclust$classification==5,])
summary(afdata[mclust$classification==6,])
```

```{r}
afdata[ , "ClusterDescription"] <- NA
n=length(afdata$Country)
i=1
while (i<=n)
{
  
  if (mclust$classification[i]==6) {
    afdata$ClusterDescription[i] <-"VeryGood"
  }  
  else if (mclust$classification[i]==2) {
    afdata$ClusterDescription[i] <-"Good"
  }  
  if (mclust$classification[i]==1) {
    afdata$ClusterDescription[i] <-"Fine"
  }  
  if (mclust$classification[i]==3) {
    afdata$ClusterDescription[i] <-"Bad"
  }  
  if (mclust$classification[i]==4) {
    afdata$ClusterDescription[i] <-"VeryBad"
  }  
  if (mclust$classification[i]==5) {
    afdata$ClusterDescription[i] <-"TheWorst"
  }
    i=i+1
}


## list of cluster assignments (pair country year changes over time)
o=order(mclust$classification)
lclust<-data.frame(afdata$Country[o],afdata$Year, afdata$ClusterDescription[o])

```


```{r}
#we visualize countries per year to see how they are changing cluster
CountryYerarCluster<-data.frame(afdata$Country,afdata$Year, afdata$ClusterDescription)

# Cluster plot
fviz_cluster(mclust, data= scaled_data,geom = "point", frame.type = "norm")

```

